package helper

import (
	"github.com/google/go-github/v43/github"
	"log"
	"strings"
)

func ExitIfError(err error) {
	if err != nil {
		// if err is generated by go-github
		if err, ok := err.(*github.ErrorResponse); ok {
			if len(err.Errors) == 0 {
				log.Fatalln(err.Message)
			}
			var messages []string
			for _, e := range err.Errors {
				messages = append(messages, e.Message)
			}
			log.Fatalln(err.Message + ": " + strings.Join(messages, ", "))
		}
		log.Fatalln(err)
	}
}
