git:
  user:
    # Your name to show in commits, can be anything you like
    name: lkxed
    email: lkxed@outlook.com
  local:
    # Your local repository path (which will be created if not exists).
    repository: /Users/lkxed/Documents/GitHub/TranslateProject
    # name of your work branch, default to <FILENAME>.
    # OPTIONS:
    #   - `master`, `main`, `translating`, etc.:
    #     To use the specified branch (which will be created if not exists).
    #
    #   - <FILENAME>:
    #     To create and use a new branch named after <FILENAME>,
    #     with illegal characters replaced by hyphens `-`.
    branch: <FILENAME>
  remote:
    upstream:
      repository: https://github.com/LCTT/TranslateProject
      branch: master
  commit:
    message: "[<ACTION>][<CATEGORY>]: <FILENAME>"
  hub:
    username: lkxed
    # To generate your own access-token, read the how-to guide below:
    # https://docs.github.com/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token#creating-a-token
    access-token:
    pull-request:
      # Defaults:
      # - <ACTION>: `手动选题`/`申领原文`/`提交译文`/`修改译文`
      # - <CATEGORY>: `news`/`talk`/`tech`
      title: "[<ACTION>][<CATEGORY>]: <FILENAME>"
      # The `body` is essentially the first comment of the PR.
      # Defaults:
      # - <STATUS>: `collected`/`being translated`/`translated`
      body: "This article is <STATUS> by <USERNAME>."

editor: "code -n -w"
browser: "open -a safari"
